# Generated by Django 3.2.6 on 2021-08-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='advuser',
            name='type_user',
            field=models.CharField(choices=[('employment', 'Работодатель'), ('applicant', 'Соискатель')], default='applicant', max_length=120),
        ),
    ]
