# Generated by Django 3.2.6 on 2021-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210807_1824'),
        ('accounts', '0002_auto_20210809_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='favourits',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.JobModel', verbose_name='Избранные вакансии'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='type_user',
            field=models.CharField(choices=[('employment', 'Работодатель'), ('applicant', 'Соискатель')], default='applicant', max_length=120, verbose_name='Тип пользователя'),
        ),
    ]
