# Generated by Django 3.2.6 on 2021-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя категории')),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('position', models.CharField(max_length=300, verbose_name='Где находится')),
                ('employment', models.CharField(choices=[('p', 'Part-Time'), ('f', 'Full-Time'), ('s', 'Free-Shedule')], default='Full-Time', max_length=120, verbose_name='Занятость')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('experience', models.CharField(choices=[('one', 'Less 1 YEAR'), ('one-three', 'From 1 to 3 YEARS'), ('more', 'More than 3 YEARS')], default='From 1 to 3 YEARS', max_length=120, verbose_name='Опыт')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Male', max_length=120, verbose_name='Пол')),
                ('responsibility', models.TextField(blank=True, null=True, verbose_name='Ответственность')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='Квалификации')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Выгоды')),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество мест в вакансии')),
                ('salary_min', models.IntegerField(verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(verbose_name='Максимальная зарплата')),
                ('image', models.ImageField(upload_to='', verbose_name='Лого вакансии')),
                ('category', models.ManyToManyField(to='jobs.JobCategory')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
