# Generated by Django 3.2.6 on 2021-08-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Категория вакансии', 'verbose_name_plural': 'Категории вакансии'},
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('portfolio_link', models.TextField(verbose_name='Ссылка на портфолио')),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='portfolio/', verbose_name='Портфолио')),
                ('coverletter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobmodel', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
