# Generated by Django 3.2.6 on 2021-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210807_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user', to='jobs.jobmodel', verbose_name='Вакансия'),
        ),
    ]
