# Generated by Django 3.2.6 on 2021-08-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_resumemodel_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий на отклик')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_message', to='jobs.resumemodel', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Сообщениe на отклик',
                'verbose_name_plural': 'Сообщения на отклики',
            },
        ),
    ]
